name: AX9T-hack👾🤖
services:
  - name: AX9T-hack👾🤖
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
